<?php

function courier_ubercart_menu()
{
  $items = array();

  $items['courier/update'] = array(    
    'page callback' => 'courier_update', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/update.inc',
  );
  
   $items['courier/update.php'] = array(    
    'page callback' => 'courier_update', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/update.inc',
  );
  
  
  $items['courier/generate_request'] = array(    
    'page callback' => 'generate_request', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/request_handler.inc',
  );   
  
  $items['admin/config/courier'] = array(    
    'title' => 'Courier Settings',
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('courier_ubercart_admin'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/admin.inc',
  );
  
  $items['admin/config/courier/mapping/product'] = array( 
    'title' => 'Courier Product Mapping',
    'page callback' => 'courier_ubercart_admin_mapping_product', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/admin_mapping.inc',
  );
  
  $items['admin/config/courier/mapping/customer'] = array(    
    'title' => 'Courier User Mapping',
    'page callback' => 'courier_ubercart_admin_mapping_user', 
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/admin_mapping.inc',
  );
  
  $items['admin/config/courier/request'] = array(    
    'title' => 'Courier Requests',
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('courier_ubercart_admin_requests'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/admin_requests.inc',
  );
  
   $items['courier'] = array(    
    'title' => '',
    'page callback' => 'courier_ubercart_courier_ws',     
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
    'file' => 'includes/webservice/courier_ws.php',
  );
  
  return $items;
}

function courier_ubercart_theme($existing, $type, $theme, $path) {
    $theme_hooks = array(
       'courier_ubercart_product_mapping_table' => array(
       'render element' => 'form',
       'file' => 'includes/admin.inc',
        ), 
        'courier_ubercart_order_table' => array(
           'render element' => 'form',
           'file' => 'includes/admin_requests.inc',
        ),
        'courier_ubercart_product_table' => array(
           'render element' => 'form',
           'file' => 'includes/admin_requests.inc',
        ),
        'courier_ubercart_customer_table' => array(
           'render element' => 'form',
           'file' => 'includes/admin_requests.inc',
        ),
         'courier_ubercart_order_mapping_table' => array(
       'render element' => 'form',
       'file' => 'includes/admin.inc',
        ),
        'courier_ubercart_request_table' => array(
       'render element' => 'form',
       'file' => 'includes/admin_requests.inc',
        ),
       'courier_ubercart_request_log_table' => array(
       'render element' => 'form',
       'file' => 'includes/admin_requests.inc',
        ),
        'courier_ubercart_customer_mapping_table' => array(
       'render element' => 'form',
       'file' => 'includes/admin.inc',
        )
    );
            
    return $theme_hooks;
}

/**
* Implementation of hook_ca_action().
*/
function courier_ubercart_ca_action() {
  $order_arg = array(
    '#entity' => 'uc_order',
    '#title' => t('Order'),
  );
 

$actions['download_order_qbpos'] = array(
    '#title' => t('Download order to Quickbooks POS'),
    '#category' => t('Order'),
    '#callback' => 'courier_ubercart_download_order_pos',
    '#arguments' => array(
      'order' => $order_arg      
    ),
  );

  return $actions;
}

function courier_ubercart_download_order_pos($order)
{       
    $order_type = "SalesReceipt";
    
    $method = strtolower(str_replace(" ", "", $order_type));
    
    include "includes/request/{$method}_Request.inc";  
    
    $m = "courier_ubercart_generate_{$method}_Request";
    
    $m(array($order));                                        
}